FROM golang:1.22-alpine

ENV PROJECT_PATH=/chirpstack-v3-to-v4

RUN apk add --no-cache make git bash
RUN go install github.com/goreleaser/goreleaser@v1.25.1
RUN git config --global --add safe.directory $PROJECT_PATH

RUN mkdir -p $PROJECT_PATH
WORKDIR $PROJECT_PATH
